# Generated by Django 3.0.4 on 2020-04-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('outpass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_details',
            name='Hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outpass.Hostel'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
        ),
        migrations.AddField(
            model_name='lectures',
            name='TaughtBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='FacultyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='LectureID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures'),
        ),
    ]
