# Generated by Django 3.0.4 on 2020-04-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20200414_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templectures',
            name='Branch',
        ),
        migrations.AddField(
            model_name='templectures',
            name='Department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academics.Department'),
            preserve_default=False,
        ),
    ]
