# Generated by Django 3.0.4 on 2020-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20200415_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='templectures',
            name='Semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
