# Generated by Django 3.0.4 on 2020-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_templectures_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='attendees',
            field=models.ManyToManyField(to='academics.stud_details'),
        ),
    ]
