# Generated by Django 3.0.5 on 2020-04-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_lectures_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='attendees',
        ),
    ]
