# Generated by Django 3.0.5 on 2020-05-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_auto_20200430_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
