# Generated by Django 3.0.5 on 2020-05-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_department_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllotedOn', models.DateField()),
                ('Attendies', models.ManyToManyField(to='academics.stud_details')),
                ('LectureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
                ('TaughtBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentLectureEnrollment',
        ),
    ]
