# Generated by Django 3.0.5 on 2020-05-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_auto_20200507_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
