# Generated by Django 3.0.5 on 2020-05-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='PresentStudents',
        ),
        migrations.CreateModel(
            name='attendies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttendenceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Attendence')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details')),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='attendie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='academics.attendies'),
            preserve_default=False,
        ),
    ]
