# Generated by Django 3.0.5 on 2020-05-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_auto_20200530_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='attendie',
        ),
    ]
