# Generated by Django 3.0.5 on 2020-05-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_remove_attendence_attendie'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendenceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttendenceDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='AttendenceDate',
        ),
        migrations.DeleteModel(
            name='attendies',
        ),
        migrations.AddField(
            model_name='attendencedetails',
            name='AttendenceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.attendence'),
        ),
        migrations.AddField(
            model_name='attendencedetails',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details'),
        ),
    ]
