# Generated by Django 3.0.5 on 2020-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_auto_20200530_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='attendanceFile',
            field=models.FileField(default=0, upload_to='media/attendance/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='attendenceDetails',
        ),
    ]
