# Generated by Django 3.0.5 on 2020-08-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_auto_20200718_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='attendies',
        ),
        migrations.CreateModel(
            name='lectureEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.stud_details')),
            ],
        ),
    ]
