# Generated by Django 3.0.5 on 2020-09-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_auto_20200827_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='lectureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('facultyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
                ('lectureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.lectures')),
            ],
        ),
    ]
